config/routes.rb
MeetingsWithGoogle::Application.routes.draw do

  get "participations/new"

  get "participations/create"

  get "participations/index"

  get "participations/destroy"

  get "participations/update"

  get "participations/show"

  resources :meetings

  resources :users

  resources :sessions,  :only =>  [:new, :create, :destroy]

  resource  :pages, :only => [:index, :show]

  resources :participations do
    resources :user_notes
  end

  resources :google_synchronizations, :only => [:new]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root              :to => 'pages#index'

end

app/models/participation.rb
# == Schema Information
#
# Table name: participations
#
#  id           :integer         not null, primary key
#  user_id      :integer
#  meeting_id   :integer
#  comments     :text
#  created_at   :datetime
#  updated_at   :datetime
#  user_as_host :boolean
#


class Participation < ActiveRecord::Base

  belongs_to  :user
  belongs_to  :meeting
  has_one     :user_note, :dependent => :destroy

  attr_accessor :user_id, :meeting_id, :comments

  accepts_nested_attributes_for :user_note

  attr_accessible  :user_note_attributes, :comments

  validate  :no_double_users
  # validate  :no_colliding_meetings_for_user

  scope :without_host, where( :user_as_host => false )



  def create_participation( meeting_id, user_id, user_as_host)

    if user_as_host
      self.user_as_host = user_as_host
    else
      self.user_as_host = false
    end

    @user = User.find(user_id)
    @user.participations << self

    @meeting = Meeting.find(meeting_id)
    @meeting.participations << self



#### !!!! TODO:Change it! Very primitive validation for Participation
    Participation.all.each do |p|
      if user.eql?(p.user)
        if !meeting.eql?(p.meeting)
          if meeting.starts_at >= p.meeting.starts_at && meeting.starts_at <= p.meeting.ends_at
            destroy
            return false
            # does it end within other meeting time?
            elsif meeting.ends_at >= p.meeting.starts_at && meeting.ends_at <= p.meeting.ends_at
              destroy
              return false
            # does it run through other meeting time?
            elsif meeting.starts_at <= p.meeting.starts_at && meeting.ends_at >= p.meeting.ends_at
              destroy
              return false
          end
        end
      end
    end
################################### End of PRIMITIVE VALIDATION #######################

    self.save

    @meeting.update_status_and_sync( :up_to_date_with_google => false )

    true
  end



  def self.find_participation(meeting_id, user_id)
    Participation.where(:meeting_id => meeting_id, :user_id => user_id).first
  end

  def destroy_participation
    meeting = self.meeting
    user = self.user
    self.destroy
    meeting.participations(true)
    user.participations(true)

    @meeting.update_status_and_sync( :up_to_date_with_google => false )

  end



protected

  def no_double_users
    Participation.all.each do |p|
      if user.eql?(p.user) & meeting.eql?(p.meeting)
        errors.add(:user, "User already participates in that meeting!")
      end
      end
  end

  def no_colliding_meetings_for_user
  #  Participation.all.each do |p|
  #    if user.eql?( p.user )
  #     if !meeting.eql?(p.meeting)
  #        puts "!!! Validation !!! id: " + meeting.id.to_s
  #      end
   #     user.meetings.each do |meet|
   #         puts "!!! FOUND TWO SAME MEETINGS !!!"
   #         if p.meeting.starts_at >= meet.starts_at && p.meeting.starts_at <= meet.ends_at
   #               errors.add(:user,  ' - You have another meeting between ' +
   #                          meet.starts_at.strftime("%R") +
   #                                           meet.ends_at.strftime("-%R"))
   #
   #         # does it end within other meeting time?
   #         elsif p.meeting.ends_at >= meet.starts_at && p.meeting.ends_at <= meet.ends_at
   #               errors.add(:user,  ' - You have another meeting between ' +
   #                             meet.starts_at.strftime("%R") +
   #                                              meet.ends_at.strftime("-%R"))
   #
   #         # does it run through other meeting time?
   #         elsif p.meeting.starts_at <= meet.starts_at && p.meeting.ends_at >= meet.ends_at
   #               errors.add(:user, ' - You have another meeting between ' +
   #                             meet.starts_at.strftime("%R") +
   #                                              meet.ends_at.strftime("-%R"))
   #         end
   #     end
   #   end
   # end
   # Participation.all.each do |p|
   #   if meeting.eql?(p.meeting)
   #     if user.eql?(p.user)
   #       puts "!!! Meeting !!! id: " + meeting.ends_at.to_s
   #       puts "!!! User !!! id: " + user.id.to_s
   #       puts "!!! Participation !! id: " + id.to_s + " p.id: " + p.id.to_s
   #       errors.add(:user, 'Dupa')
   #     end
   #   end
   # end
   # puts "!!! Meeting.id: " + meeting.object_id.to_s
  end

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  before_filter :authorize_user

  def new
    @participation = Participation.new
    #@user_note = @participation.build_user_note

    @meeting = Meeting.find(params[:meeting_id])
    @user = User.find(session[:user_id])
    @user_as_host = params[:user_as_host]


    respond_to do |format|

      format.html
      format.xml  { render :xml => @participation }
    end
  end

  def create
    @participation = Participation.new
    respond_to do |format|
      if @participation.create_participation( params[:meeting_id], params[:user_id],
                                         params[:user_as_host])
        format.html { redirect_to meetings_path}
        format.xml  { render :xml => @participation }
      else
        format.html { redirect_to meetings_path, :notice => "You already have meeting at that time"}
        format.xml  { render :xml => @participation.errors, :status => :unprocessable_entity }

      end
    end
  end

  def index
    if signed_in?
      @user = User.find(session[:user_id])
     #@meetings = @user.meetings.all_active
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
      @participations = Participation.where( :user_id => @user )
      @meetings ||= @user.meetings.all_active.ordered.by_month( @date )
    else
      respond_to do |format|

        format.html { redirect_to meetings_path}
        format.xml  { head :ok}
      end
    end
  end

  def destroy
    @participation = Participation.find_participation(params[:meeting_id], params[:user_id])
    @participation.destroy_participation
    respond_to do |format|

      format.html { redirect_to meetings_path}
      format.xml  { head :ok}
    end
  end

  def update
    @participation = Participation.find_participation( params[:meeting_id], params[:user_id] )

  end

  def show
    puts "dupa"
  end

end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/create.html.haml
%h1 Participations#create
%p Find me in app/views/participations/create.html.haml

app/views/participations/destroy.html.haml
%h1 Participations#destroy
%p Find me in app/views/participations/destroy.html.haml

app/views/participations/index.html.haml
%h1 Your meetings

#meetings-list
  =render "shared/meetings_index", :@user => @user, :@meetings => @meetings
#meetings-date-nav
  .months-nav
    .prev
      = link_to " << ", participations_path( :date => @date.beginning_of_month - 1 ), :remote => true
    .text
      = @date.strftime("%B")
    .next
      = link_to " >> ", participations_path( :date => @date.end_of_month + 1 ), :remote => true

app/views/participations/index.js.erb
$("#meetings-list").html("<%= escape_javascript(render("shared/meetings_index")) %>");
$("#meetings-date-nav .text").html("<%= @date.strftime("%B") %>");
$("#meetings-date-nav .months-nav .prev a").attr("href", "/participations?date=<%= @date.beginning_of_month - 1 %>  ");
$("#meetings-date-nav .months-nav .next a").attr("href", "/participations?date=<%= @date.end_of_month + 1 %>  ");

$("#meetings-list").parent().delegate(".meeting-box", "hover", function() {
    var original_state = $(".title").css("background-color");
        $(".meeting-box").hover(
            function(){
                $(this).css("background-color", "#DDDDDD");
            },
            function(){
                $(this).css("background-color", original_state);
            }
        )
    });

app/views/participations/new.html.haml
= render(:partial => "shared/meetings_list", :locals => {:@meeting => @meeting})

%h3 Participation list
%table
  %tr
    %th Name

  -@meeting.attendees.each do |user|
    %tr
      %td= user.name

-if @user.already_participates(@meeting)
  %h4 Your notes
  = fields_for :participation do |f|
    .field
      = f.text_area :comments , :rows => 3
    .actions
      = f.submit "Add note"


-if @user.already_participates(@meeting)
  = button_to  "Resign", {:controller => "participations", :action => "destroy",
                          :meeting_id => @meeting.id, :user_id => session[:user_id] }, :method => :delete
-else
  -if @meeting.has_no_host?
    = link_to 'Host', {:action => "create", :user_as_host => true,
                        :meeting_id => @meeting.id, :user_id => session[:user_id]}
    \|
  -if  @meeting.has_free_places?
    = link_to  "Attend", {:action => "create", :meeting_id => @meeting.id,
                         :user_id => session[:user_id]}
\|
= link_to "Back", meetings_path