config/routes.rb
MeetingsWithGoogle::Application.routes.draw do

  get "participations/new"

  get "participations/create"

  get "participations/index"

  get "participations/destroy"

  get "participations/update"

  get "participations/show"

  resources :meetings

  resources :users

  resources :sessions,  :only =>  [:new, :create, :destroy]

  resource  :pages, :only => [:index, :show]

  resources :participations do
    resources :user_notes
  end

  resources :google_synchronizations, :only => [:new]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root              :to => 'pages#index'

end

app/models/meeting.rb
# == Schema Information
#
# Table name: meetings
#
#  id                     :integer         not null, primary key
#  starts_at              :datetime
#  ends_at                :datetime
#  title                  :string(255)
#  description            :text
#  place                  :string(255)
#  total_places           :integer
#  google_event_id        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  up_to_date_with_google :boolean         default(FALSE)
#  deleted                :boolean         default(FALSE)
#



class Meeting < ActiveRecord::Base

  # it allows tracking changes in model objects - see declaration of validations
  include ActiveModel::Dirty



  has_many    :participations, :dependent => :destroy
  has_many    :users, :through => :participations

  attr_accessible   :starts_at, :ends_at, :title, :description,
                  :place, :tutor, :available_places, :total_places,
                  :google_event_id, :up_to_date_with_google, :deleted,
                  :start_time, :end_time, :meeting_date

  #attr_accessible :start_time, :end_time, :meeting_date

  scope :all_active, where(:deleted => false)

  scope :deleted, where( :deleted => true )

  scope :outdated, where( :up_to_date_with_google => false )

  scope :all_needing_update, where("deleted = ? OR up_to_date_with_google = ?", true, false)

  scope :ordered, order("starts_at ASC")

  scope :by_month, lambda { |date| { :conditions => { :starts_at => date.beginning_of_month..date.end_of_month} } }

  validate  :dates_cannot_collide
  validate  :cannot_end_before_start


##############################################

### CREATING Meeting

  ## uses a method to construct proper params - it's due ugly datetime select in new_meeting form
  def self.new_meeting( params )
    params = ends_at_param_builder( params )
    Meeting.new( params )
  end

  def save_with_sync
    if self.save
      update_status_and_sync( :up_to_date_with_google => false )
      true
    else
      false
    end
  end

### end of CREATING Meeting

##############################################


##############################################

### READING Meeting

  def self.find_meeting( params )
    @meeting ||= Meeting.find( params )
  end

### end of READING Meeting


##############################################

### UPDATING Meeting

  ## uses a method to construct proper params - it's due ugly datetime select in update_meeting form

  def update_status_and_sync( status )
    update_attributes( status )
    sync = GoogleSynchronization.new
    if sync.update_google_cal
      update_attributes( :up_to_date_with_google => true )
      true
    else
      false
    end

  end

  def update_attributes_with_sync( params )
    params = ends_at_param_builder( params )
    if update_attributes( params )
      update_status_and_sync( :up_to_date_with_google => false )
      true
    else
      false
    end
  end

### end of UPDATING Meeting

##############################################

### DESTROYING Meeting

  def destroy_and_sync
    if update_status_and_sync(:deleted => true)
      self.destroy
      true
    else
     false
    end
  end

### end of DESTROYING Meeting

#### Date formatting

  def meeting_date( part = nil )
    if part
      starts_at.send( :strftime, "#{part}" )
    else
      starts_at.strftime("%d %b") unless starts_at.nil?
    end
  end

  def meeting_date=(date)
    date
  end

  def start_time
    starts_at.to_s(:time) unless starts_at.nil?
  end

  def start_time=(time)
    time
  end

  def end_time
    ends_at.to_s(:time)   unless ends_at.nil?
  end

  def end_time=(time)
    time
  end

#  def duration
#    distance_of_time_in_words(self.starts_at, self.ends_at)
#  end

#### end of Date formatting

  def has_free_places?
    available_places > 0 ? true : false
  end

  def has_no_host?
    !self.host_present?
  end

  def available_places
    total_places - participations.without_host.size
  end

  def host
    if host_present?
      participations.each do |p|
        if p.user_as_host
          return p.user
        end
      end
    end
  end

  def attendees(with_host = false)
    attendees = []
    attenders = with_host ? participations : if participations.empty?
                                                participations
                                             else
                                                participations.without_host
                                             end
    attenders.collect { |p| attendees << p.user }
    attendees
  end


  def attendees_hash(with_host = false)
    if attendees(with_host).empty?
      return []
    end
    attendees(with_host).inject([]) do |result,element|
      hash = {}
      hash[:name] = element.name
      hash[:email] = element.email
      result << hash
    end
  end


  def description_for_google_calendar
    description_content = self.description.dup
    description_content += "\n"
    if host.present?
      description_content += "\nTutor: #{host.email}"
    end
    description_content += "\nMeeting ID: #{id}"
  end


protected

  # building ends_at date from date only component of starts_at and time only component of ends_at
  # it's used to simplify meeting creation form

  #



  def host_present?
      participations.each do |p|
        if p.user_as_host
          return true
        end
      end
    false
  end

  # I know it's ridiculous to have 2 same methods
  # Any way to have same method for class and object?
  def self.ends_at_param_builder(params)
    start_date = params[:meeting_date] + " " + params[:start_time]
    if params[:start_time] > params[:end_time]
      meeting_end_date = (Date.parse( params[:meeting_date] ) + 1.day ).to_s
      end_date =  meeting_end_date + " " + params[:end_time]
    else
      end_date =  params[:meeting_date] + " " + params[:end_time]
    end

    params[:starts_at] = Time.parse( start_date )
    params[:ends_at]  = Time.parse( end_date )
    params
  end

  def ends_at_param_builder(params)
    start_date = params[:meeting_date] + " " + params[:start_time]

    if params[:start_time] > params[:end_time]
      meeting_end_date = (Date.parse( params[:meeting_date] ) + 1.day ).to_s
      end_date =  meeting_end_date + " " + params[:end_time]
    else
      end_date =  params[:meeting_date] + " " + params[:end_time]
    end

    params[:starts_at] = Time.parse( start_date )
    params[:ends_at]  = Time.parse( end_date )
    params
  end

  def self.places
    places = []
    Meeting.all_active.collect {|m| places << m.place}
    places
  end

  def self.places_sorted_by_times_used

    hash = Meeting.places.inject({}) do | result, array_value |
	    key_from_array_value = array_value.downcase.gsub(/\s+/, "_").to_sym
	    if result.has_key?( key_from_array_value )
	      result[ key_from_array_value ] += 1
	    else
	      result[ key_from_array_value ] = 1
	    end
	  result
    end

    hash = hash.sort_by { |element| element.last }

    array = hash.reverse.inject([]) do |result,hash_element|
      result << hash_element.first.to_s.capitalize
    end



  end


  def not_comparing_same_meetings?(meeting)
    !id.eql?(meeting.id)
  end

  def comparing_meetings_with_same_venue?(meeting)
    place.eql?(meeting.place)
  end

  def meeting_starts_within_other?(meeting)
    starts_at >= meeting.starts_at && starts_at <= meeting.ends_at
  end

  def meeting_ends_within_other?(meeting)
    ends_at >= meeting.starts_at && ends_at <= meeting.ends_at
  end

  def meeting_runs_through_other?(meeting)
    starts_at <= meeting.starts_at && ends_at >= meeting.ends_at
  end

  def produce_meeting_date_collision_error(meeting, symbol)
    errors.add(symbol,  ' - There is another meeting between ' +
                         meeting.starts_at.strftime("%R") +
                                           meeting.ends_at.strftime("-%R"))
  end

### Validations

  # Check if there is no other meeting in that time
  def dates_cannot_collide
   # let's check if date or place has changed - if not then dont bother with validatiot
    if starts_at_changed? || ends_at_changed? || place_changed?
      Meeting.all_active.each do |meeting|
        if not_comparing_same_meetings?(meeting)
          if comparing_meetings_with_same_venue?(meeting)
            # does it start within other meeting time?
            # TODO: DRY it out
            if meeting_starts_within_other?(meeting)
              produce_meeting_date_collision_error(meeting, :starts_at)
            # does it end within other meeting time?
            elsif meeting_ends_within_other?(meeting)
              produce_meeting_date_collision_error(meeting, :ends_at)
            # does it run through other meeting time?
            elsif meeting_runs_through_other?(meeting)
              produce_meeting_date_collision_error(meeting, :starts_at)
            end
          end
        end
      end
    end
  end

  # Until there's no nice date picking tool let's check if meeting has proper start-end times
  def cannot_end_before_start
    if starts_at_changed? || ends_at_changed?
      if starts_at >= ends_at
        errors.add(:ends_at, '- You can\'t finish meeting before it starts :)' )
      end
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController



  before_filter :authorize_admin, :except  => [:index, :show]

  # GET /meetings
  # GET /meetings.xml
  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @meetings ||= Meeting.ordered.by_month( @date )
    if signed_in?
      @user = User.find(session[:user_id])
    end

    respond_to do |format|
      format.html
      format.xml { render :xml => @metings }
      format.js
    end

  end

  # GET /meetings/1
  # GET /meetings/1.xml
  def show
    @meeting = Meeting.find_meeting(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.xml
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @meeting }
    end
  end

  # POST /meetings
  # POST /meetings.xml
  def create
    @meeting = Meeting.new_meeting(params[:meeting])

    respond_to do |format|
      if @meeting.save_with_sync
        format.html { redirect_to(meetings_url, :notice => 'Meeting was successfully created.') }
        format.xml  { render :xml => @meeting, :status => :created, :location => @meeting }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end


  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end


  # PUT /meetings/1
  # PUT /meetings/1.xml
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes_with_sync(params[:meeting])
        format.html { redirect_to(meetings_url, :notice => 'Meeting was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.xml
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy_and_sync

    respond_to do |format|
      format.html { redirect_to(meetings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def meeting_or_participation(meeting)
    if admin?
      meeting
    else
      new_participation_path( :meeting_id => meeting.id )
    end
  end

  def participation_params(meeting, host)
    {:controller => "participations", :action => "create", :user_as_host => host, :meeting_id => meeting.id, :user_id => session[:user_id]}
  end
end

app/views/meetings/_form.html.haml
= form_for @meeting do |f|
  -if @meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"
      %ul
        - @meeting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :starts_at
    = f.datetime_select :starts_at, :minute_step => 15
  .field
    = f.label :ends_at
    = f.datetime_select :ends_at , :minute_step => 15  , :discard_year => true, :discard_month => true
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :place
    = f.text_field :place
  .field
    = f.label :total_places
    = f.text_field :total_places
  .actions
    = f.submit 'Save'

app/views/meetings/edit.html.haml
%h1 Editing meeting

%p TODO: Editing dates needs to be fixed
%p IT DOESN'T WORK WHEN YOU NEED TO SET UP MEETING OVER MIDNIGHT AND WILL MESS UP THINGS

= render 'shared/form_for_meeting'

app/views/meetings/index.html.haml
%h1 Listing meetings
.bottom-buttons-and-links
- if admin?
  = link_to "New Meeting", new_meeting_path
#meetings-list
  =render "shared/meetings_index", :@user => @user, :@meetings => @meetings

#meetings-date-nav
  .months-nav
    .prev
      = link_to " << ", meetings_path( :date => @date.beginning_of_month - 1 ), :remote => true
    .text
      = @date.strftime("%B")
    .next
      = link_to " >> ", meetings_path( :date => @date.end_of_month + 1 ), :remote => true

app/views/meetings/index.js.erb
$("#meetings-list").html("<%= escape_javascript(render("shared/meetings_index")) %>");
$("#meetings-date-nav .text").html("<%= @date.strftime("%B") %>");
$("#meetings-date-nav .months-nav .prev a").attr("href", "/meetings?date=<%= @date.beginning_of_month - 1 %>  ");
$("#meetings-date-nav .months-nav .next a").attr("href", "/meetings?date=<%= @date.end_of_month + 1 %>  ");

$("#meetings-list").parent().delegate(".meeting-box", "hover", function() {
    var original_state = $(".title").css("background-color");
        $(".meeting-box").hover(

            function(){
                $(this).css("background-color", "#DDDDDD");
            },
            function(){
                $(this).css("background-color", original_state);
            }
        )
    });

app/views/meetings/index_backup.html.haml
%h1 Listing meetings

#meetings-list
  %table
    %tr
      %th
      %th Meeting time
      %th
      %th Title
      %th Place
      %th Tutor
      %th Places
      %th
      %th
      %th

    - @meetings.each do |meeting|
      %tr
        %td.m_day #{meeting.meeting_date}
        %td.m_time #{meeting.start_time} to #{meeting.end_time}
        %td
        %td= meeting.title
        %td= meeting.place
        -if meeting.has_no_host?
          %td
        -else
          %td= meeting.host.name
        %td= meeting.available_places
        - if signed_in?
          %td= link_to 'Show', meeting_or_participation(meeting)
          -if admin?
            %td= link_to 'Edit', edit_meeting_path(meeting)
            %td= button_to 'Destroy', meeting , :confirm => 'Are you sure?', :method => :delete
          -else
            -if @user.already_participates(meeting)
              %td= button_to  "Resign", {:controller => "participations", :action => "destroy",
                                      :meeting_id => meeting.id, :user_id => @user.id}, :method => :delete
            -else
              -if meeting.has_no_host?
                %td= link_to 'Host', participation_params(meeting, true)
              -if meeting.has_free_places?
                %td= link_to  "Attend", participation_params(meeting, false)

%br
- if admin?
  = link_to 'New Meeting', new_meeting_path

app/views/meetings/new.html.haml
%h1 New meeting

= render 'shared/form_for_meeting'

app/views/meetings/show.html.haml
= render(:partial => "shared/meetings_list", :locals => {:@meeting => @meeting})
%p
  %b Total places:
  = @meeting.total_places

= link_to 'Edit', edit_meeting_path(@meeting)
\|
= link_to 'Back', meetings_path