config/routes.rb
MeetingsWithGoogle::Application.routes.draw do

  get "participations/new"

  get "participations/create"

  get "participations/index"

  get "participations/destroy"

  get "participations/update"

  get "participations/show"

  resources :meetings

  resources :users

  resources :sessions,  :only =>  [:new, :create, :destroy]

  resource  :pages, :only => [:index, :show]

  resources :participations do
    resources :user_notes
  end

  resources :google_synchronizations, :only => [:new]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root              :to => 'pages#index'

end

app/views/shared/_form_for_meeting.html.haml
= form_for @meeting do |f|
  -if @meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"
      %ul
        - @meeting.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :meeting_date, "Day"
    = f.text_field :meeting_date
  .field
    = f.label :start_time
    = f.text_field :start_time
  .field
    = f.label :end_time
    = f.text_field :end_time
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :place
    = f.select  :place, options_for_select(Meeting.places_sorted_by_times_used, :place), {:include_blank => true}
  .field
    = f.label :place
    = f.text_field :place
  .field
    = f.label :total_places
    = f.text_field :total_places
  .actions
    = f.submit 'Save'
    #{ link_to 'Back', meetings_path }

app/views/shared/_form_for_user.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/shared/_header.html.haml
%h1 Meetings with Google
%h3 Store your schedule to Google Calendar

app/views/shared/_main_menu.html.haml
%ul
  %li=  link_to "Meetings", meetings_path
  -if admin?
    %li=  link_to "Users",    users_path
  -if signed_in?
    -if this_user.attends_any_meetings?
      %li=  link_to "My meetings", {:controller => "participations", :action => "index",
                                    :user_id  => this_user.id}
    %li   Signed in as #{this_user.name}
    %li=  link_to "Sign out", signout_path
  -else
    - if !(controller.controller_name.eql?("sessions"))
      %li=  link_to "Sign in",  signin_path

app/views/shared/_meetings_index.html.haml
- @meetings.each do |meeting|
  .meeting-box
    .date
      %strong
        = meeting.meeting_date( MONTH )
      %big
        = meeting.meeting_date( DAY )
      %small
        = meeting.meeting_date( YEAR )
    .time-span
      #{meeting.start_time} to #{meeting.end_time}
    .title
      %h3
        = meeting.title
    .notes
      %p
        %span
          - if Time.now < meeting.starts_at
            #{distance_of_time_in_words_to_now( meeting.starts_at )} to the meeting
          - else
            Meeting finished
    .links
      - if regular_user?
        = render "meetings/partials/links_for_user", :meeting => meeting, :@user => @user
      - if admin?
        = render "meetings/partials/links_for_admin", :meeting => meeting

app/views/shared/_meetings_list.html.haml
%p
  %b Starts at:
  = @meeting.starts_at
%p
  %b Ends at:
  = @meeting.ends_at
%p
  %b Title:
  = @meeting.title
%p
  %b Description:
  = @meeting.description
%p
  %b Place:
  = @meeting.place
%p
  %b Tutor:
  -if @meeting.has_no_host?

  -else
    = @meeting.host.name

app/views/shared/_users_list.html.haml
%table
  %tr
    %th Name
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      - if admin?
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        - if !current_user(user.id)
          %td= button_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete,
                                          :title => "Will delete user #{user.name}"